name: "CI"

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install tesseract
        run: sudo apt-get install -y tesseract-ocr
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8388f20e6a9c43cd241131b678469a9f89579f37
        with:
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
